name: Generate
on: push

permissions:
  contents: write

jobs:
  Generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm add -D vitepress
    - run: npm run docs:build
    - uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: docs/.vitepress/dist